default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/status_development

test:
  <<: *default
  database: db/status_test

production:
  <<: *default
  database: db/status_production
