# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c106ccb881049f57ccaf6c9a2deaa17344435fff42fbb1538e951ba1b7d8c0685c757d4c3416adf24529caa9b95d6547582c5b26b3e39e4052a954ce1b4fd014
  auth_username: litmus
  auth_password: secret

test:
  secret_key_base: eb90b7c3bf335b4d18aec61d799bad69e44181cb53c7bdb8c49d2315208d0b751076327ba1b56b57f8212aba432b1da42630a14aa1e78ba75cfbaa9630615faf
  auth_username: litmus
  auth_password: secret

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth_username: litmus
  auth_password: secret
